In [2]:
# for reading data
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils

# for modeling
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split

import plotly as plt



example website
https://medium.com/luca-chuangs-bapm-notes/build-a-neural-network-in-python-multi-class-classification-e940f74bd899

In [3]:
#read in the data
#take input from provisional database (csv)
# Load the csv file from GitHub
url = 'https://raw.githubusercontent.com/mandymccabe/Final_Project/janet_branch/Data/Final_Project_Full.csv'
url2= 'https://raw.githubusercontent.com/mandymccabe/Final_Project/main/Resources/all_responses_coded.csv'
df = pd.read_csv(url, index_col=0)
df2 = pd.read_csv(url2, index_col=0)

Exploratory Analysis

In [6]:
len(df)

1021

In [7]:
len(df2)

1021

In [15]:
# number of rows and columns
df.shape

(1021, 23)

In [16]:
# number of rows and columns
df2.shape

(1021, 65)

In [18]:
# check for missing data
df.isna().sum()

political_views                   0
trust_in_press                    0
online_paid_access                0
impression_with_access_to_data    0
trump_as_president                0
age                               0
gender                            0
income                            0
us_region                         0
startdate                         0
enddate                           0
new_york_times                    0
wall_street_journal               0
usa_today                         0
washington_post                   0
fox_news                          0
breitbart                         0
cnn                               0
buzzfeed                          0
huffington_post                   0
time                              0
us_news_and_world_report          0
other                             0
dtype: int64

In [26]:
# check for missing data
df2.isna().sum()

RespondentID    0
A1              0
A2              0
A3              0
A4              0
A5              0
A6              0
A7              0
A8              0
A9              0
A10             0
A11             0
A12             0
A13             0
A14             0
A15             0
A16             0
A17             0
A18             0
A19             0
A20             0
A21             0
A22             0
A23             0
A24             0
A25             0
A26             0
A27             0
A28             0
A29             0
A30             0
A31             0
A32             0
A33             0
A34             0
A35             0
A36             0
A37             0
A38             0
A39             0
A40             0
A41             0
A42             0
A43             0
A44             0
A45             0
A46             0
A47             0
A48             0
A49             0
A50             0
A51             0
A52             0
A53             0
A54             0
A55       

Analysis Phase

In [27]:
clean_df2= df2.drop(['A1','A2','A3','A4','A5','A21','StartDate','EndDate'], axis=1)

In [18]:
PoliticalViews = df.filter(["political_views"], axis=1)
PoliticalViews.head()

political_views
respondentid                
6176264298          Moderate
6176263960          Moderate
6176258621           Liberal
6176257082           Liberal
6176256111           Liberal

In [19]:
merged_dfs = pd.merge(clean_df2, PoliticalViews, how='outer', left_on=["RespondentID"], right_on=['respondentid'])
merged_dfs.head()

RespondentID  A6  A7  A8  A9  A10  A11  A12  A13  A14  ...  A54  A55  A56  \
0    6176264298   0   1   0   0    1    0    1    0    0  ...    0    0    0   
1    6176263960   0   1   0   0    1    0    0    0    0  ...    0    0    0   
2    6176258621   0   1   0   0    1    0    0    1    0  ...    0    0    0   
3    6176257082   0   1   0   0    0    0    0    1    0  ...    0    1    0   
4    6176256111   0   1   0   0    1    1    1    0    0  ...    0    0    1   

   A57  A58  A59  A60  A61  A62  political_views  
0    1    0    0    0    0    0         Moderate  
1    0    0    0    1    0    0         Moderate  
2    0    0    0    1    0    0          Liberal  
3    1    0    0    0    0    0          Liberal  
4    1    0    0    0    0    0          Liberal  

[5 rows x 58 columns]

In [81]:
# split into X and Y
Y = merged_dfs['political_views']
X = merged_dfs.drop(['political_views', 'RespondentID'], axis=1)

print(X.shape)
print(Y.shape)

# convert to numpy arrays
X = np.array(X)

(1021, 56)
(1021,)


In [82]:
# show Y
Y.head(50)

0              Moderate
1              Moderate
2               Liberal
3               Liberal
4               Liberal
5               Liberal
6          Conservative
7              Moderate
8              Moderate
9     Very Conservative
10             Moderate
11             Moderate
12         Conservative
13             Moderate
14             Moderate
15              Liberal
16              Liberal
17         Conservative
18             Moderate
19         Very Liberal
20             Moderate
21         Conservative
22             Moderate
23             Moderate
24             Moderate
25              Liberal
26             Moderate
27             Moderate
28         Conservative
29         Conservative
30         Very Liberal
31             Moderate
32         Conservative
33              Liberal
34              Liberal
35         Conservative
36             Moderate
37              Liberal
38             Moderate
39             Moderate
40             Moderate
41              

In [83]:
# work with labels
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)



In [84]:
print(encoded_Y)

[2 2 1 ... 2 2 2]


In [85]:
print(dummy_y)

[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [124]:
#split into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, dummy_y, random_state=3, train_size=0.80)

In [125]:
number_inputs= len(X[0])
hidden_nodes_1 = 8
hidden_nodes_2 =8
hidden_nodes_3=8


In [126]:
# build a model
model = Sequential()
model.add(Dense(units=hidden_nodes_1, activation='relu', input_dim= number_inputs))
#model.add(Dense(units=hidden_nodes_2, activation='relu'))
#model.add(Dense(units=hidden_nodes_3, activation='relu'))
model.add(Dense(5, activation='softmax'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_14 (Dense)            (None, 8)                 456       
                                                                 
 dense_15 (Dense)            (None, 5)                 45        
                                                                 
Total params: 501
Trainable params: 501
Non-trainable params: 0
_________________________________________________________________


In [127]:
# compile the model
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', # this is different instead of binary_crossentropy (for regular classification)
              metrics=['accuracy'])

In [128]:
import keras
from keras.callbacks import EarlyStopping

# early stopping callback
# This callback will stop the training when there is no improvement in  
# the validation loss for 10 consecutive epochs.  
es = keras.callbacks.EarlyStopping(monitor='val_loss', 
                                   mode='min',
                                   patience=10, 
                                   restore_best_weights=True) # important - otherwise you just return the last weigths...



In [129]:
# now we just update our model fit call
history = model.fit(X_train,
                    y_train,
                    epochs=100, 
                    
                   
                    #batch_size=10,
                    #shuffle=True,
                    validation_split=0.2)
                    #verbose=1
                    #callbacks=[es],

Epoch 1/100
21/21 [==============================] - 4s 101ms/step - loss: 1.6361 - accuracy: 0.1564 - val_loss: 1.5724 - val_accuracy: 0.2561
Epoch 2/100
21/21 [==============================] - 0s 22ms/step - loss: 1.5627 - accuracy: 0.2408 - val_loss: 1.5139 - val_accuracy: 0.3049
Epoch 3/100
21/21 [==============================] - 0s 23ms/step - loss: 1.5101 - accuracy: 0.3190 - val_loss: 1.4593 - val_accuracy: 0.3476
Epoch 4/100
21/21 [==============================] - 0s 24ms/step - loss: 1.4628 - accuracy: 0.3696 - val_loss: 1.4104 - val_accuracy: 0.3720
Epoch 5/100
21/21 [==============================] - 0s 21ms/step - loss: 1.4228 - accuracy: 0.3957 - val_loss: 1.3703 - val_accuracy: 0.4329
Epoch 6/100
21/21 [==============================] - 0s 23ms/step - loss: 1.3893 - accuracy: 0.4003 - val_loss: 1.3357 - val_accuracy: 0.4329
Epoch 7/100
21/21 [==============================] - 1s 26ms/step - loss: 1.3585 - accuracy: 0.4187 - val_loss: 1.3043 - val_accuracy: 0.4390
Epoch

In [107]:

history_dict = history.history

# learning curve
# accuracy
acc = history_dict['accuracy']
val_acc = history_dict['val_accuracy']


In [108]:
acc

[0.09313725680112839,
 0.17401960492134094,
 0.26838234066963196,
 0.3321078419685364,
 0.3958333432674408,
 0.41911765933036804,
 0.43995097279548645,
 0.44117647409439087,
 0.45588234066963196,
 0.4583333432674408,
 0.468137264251709,
 0.4730392098426819,
 0.48161765933036804,
 0.49142158031463623,
 0.48774510622024536,
 0.4950980246067047,
 0.49754902720451355,
 0.5036764740943909,
 0.5122548937797546,
 0.5061274766921997,
 0.5122548937797546,
 0.5085784196853638,
 0.5098039507865906,
 0.5110294222831726,
 0.5134803652763367,
 0.5147058963775635,
 0.5183823704719543,
 0.5196078419685364,
 0.5171568393707275,
 0.529411792755127,
 0.5245097875595093,
 0.5232843160629272,
 0.529411792755127,
 0.5257353186607361,
 0.531862735748291,
 0.5343137383460999,
 0.533088207244873,
 0.5416666865348816,
 0.5343137383460999,
 0.5392156839370728,
 0.5428921580314636,
 0.5404411554336548,
 0.5428921580314636,
 0.5465686321258545,
 0.5477941036224365,
 0.5490196347236633,
 0.5477941036224365,
 0.5539

In [109]:
val_acc

[0.12195122241973877,
 0.2780487835407257,
 0.3073170781135559,
 0.3804877996444702,
 0.43414634466171265,
 0.46341463923454285,
 0.44878047704696655,
 0.4829268157482147,
 0.4878048896789551,
 0.502439022064209,
 0.49268293380737305,
 0.507317066192627,
 0.4878048896789551,
 0.4829268157482147,
 0.4829268157482147,
 0.47804877161979675,
 0.4682926833629608,
 0.46341463923454285,
 0.47804877161979675,
 0.4829268157482147,
 0.47804877161979675,
 0.4829268157482147,
 0.4878048896789551,
 0.4829268157482147,
 0.4878048896789551,
 0.497560977935791,
 0.4878048896789551,
 0.47804877161979675,
 0.4585365951061249,
 0.46341463923454285,
 0.47804877161979675,
 0.4731707274913788,
 0.4682926833629608,
 0.4878048896789551,
 0.4878048896789551,
 0.47804877161979675,
 0.47804877161979675,
 0.4829268157482147,
 0.4682926833629608,
 0.4829268157482147,
 0.4878048896789551,
 0.49268293380737305,
 0.4829268157482147,
 0.497560977935791,
 0.4878048896789551,
 0.49268293380737305,
 0.4878048896789551,
 

In [110]:
# loss
loss = history_dict['loss']
val_loss = history_dict['val_loss']


In [111]:
loss

[1.795781135559082,
 1.6715991497039795,
 1.6056666374206543,
 1.5600543022155762,
 1.516451358795166,
 1.4713692665100098,
 1.4247808456420898,
 1.3797229528427124,
 1.3410789966583252,
 1.308462142944336,
 1.2808786630630493,
 1.2572420835494995,
 1.2369824647903442,
 1.2192777395248413,
 1.204612374305725,
 1.1910240650177002,
 1.179001808166504,
 1.1686663627624512,
 1.1593396663665771,
 1.1498485803604126,
 1.1415613889694214,
 1.1342507600784302,
 1.1287453174591064,
 1.1223556995391846,
 1.1152454614639282,
 1.1111047267913818,
 1.1048023700714111,
 1.099231243133545,
 1.0950183868408203,
 1.0911133289337158,
 1.0877885818481445,
 1.0818811655044556,
 1.0784595012664795,
 1.073861002922058,
 1.0718730688095093,
 1.0670161247253418,
 1.0648720264434814,
 1.061124563217163,
 1.0576692819595337,
 1.0552257299423218,
 1.0518981218338013,
 1.0491769313812256,
 1.046646237373352,
 1.0463069677352905,
 1.0411545038223267,
 1.0387628078460693,
 1.0366487503051758,
 1.0342061519622803,
 

In [112]:
val_loss

[1.6965566873550415,
 1.6145786046981812,
 1.5635448694229126,
 1.5219385623931885,
 1.4816088676452637,
 1.437052845954895,
 1.3950992822647095,
 1.3583325147628784,
 1.3265403509140015,
 1.301108479499817,
 1.2823749780654907,
 1.2657420635223389,
 1.2537750005722046,
 1.2437067031860352,
 1.2339812517166138,
 1.2262667417526245,
 1.2190719842910767,
 1.2130768299102783,
 1.2075690031051636,
 1.2030638456344604,
 1.199558138847351,
 1.196015477180481,
 1.1940054893493652,
 1.1914921998977661,
 1.1875858306884766,
 1.1852315664291382,
 1.184106469154358,
 1.182012915611267,
 1.180153489112854,
 1.1808751821517944,
 1.1782324314117432,
 1.1778852939605713,
 1.1774616241455078,
 1.1768954992294312,
 1.1758064031600952,
 1.1760915517807007,
 1.1761428117752075,
 1.1761703491210938,
 1.1764051914215088,
 1.1764177083969116,
 1.1774184703826904,
 1.1770682334899902,
 1.177207589149475,
 1.1766109466552734,
 1.1787484884262085,
 1.1792142391204834,
 1.1797361373901367,
 1.1809182167053223,


In [113]:

# range of X (no. of epochs)
epochs = range(1, len(acc) + 1)
epochs



range(1, 101)

In [130]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

preds = model.predict(X_test) # see how the model did!



7/7 [==============================] - 0s 6ms/step


In [131]:
print(preds) 

[[0.07019402 0.23786782 0.64677685 0.02832769 0.01683367]
 [0.02353662 0.6151607  0.22966893 0.00108934 0.13054438]
 [0.07779175 0.19116233 0.50134313 0.01277174 0.21693099]
 ...
 [0.1687172  0.44110325 0.16772674 0.1539542  0.06849862]
 [0.44153476 0.03676447 0.49908906 0.0207578  0.00185397]
 [0.68673855 0.03215686 0.12499909 0.15201494 0.00409061]]


In [132]:
#preds2 = np.argmax(preds, axis=1)
#preds2

In [133]:
print(np.sum(preds[0]))

1.0000001


In [136]:
# Almost a perfect prediction
# actual is left, predicted is top
# names can be found by inspecting Y
matrix = confusion_matrix(y_test.argmax(axis=1), preds.argmax(axis=1))
matrix

array([[21,  1, 20,  3,  0],
       [ 1, 16, 19,  0,  5],
       [12, 19, 52,  1,  2],
       [ 7,  1,  1,  1,  1],
       [ 2,  7,  8,  0,  5]], dtype=int64)

In [138]:
print(classification_report(y_test.argmax(axis=1), preds.argmax(axis=1)))

              precision    recall  f1-score   support

           0       0.49      0.47      0.48        45
           1       0.36      0.39      0.38        41
           2       0.52      0.60      0.56        86
           3       0.20      0.09      0.13        11
           4       0.38      0.23      0.29        22

    accuracy                           0.46       205
   macro avg       0.39      0.36      0.36       205
weighted avg       0.45      0.46      0.45       205



combine "very" categories? 19.3.3